development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: development_cathub
  pool: 50
  username: vlad
  password: "1"

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: test_cathub
  pool: 50
  username: vlad
  password: "1"

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: production_cathub
  pool: 50
  username: vlad
  password: "1"

